language: ruby

os: linux

services: docker

sudo: required

dist: bionic

arch: ppc64le

#script: chmod +x ./build.sh; sudo ./build.sh

script: 
   - sudo docker run -t centos:latest bash -c 'dnf update -y'
   - sudo docker run --rm alpine:latest ls -l
   - sudo docker run --rm fedora:32 bash -c 'dnf update'
   - sudo docker run --rm ubuntu:20.04 'apt-get update; apt-get install -y git'
   #- sudo docker run -t ppc64le/debian:latest bash -c 'cat /sys/module/overlay/parameters/metacopy; apt update -y; apt-get upgrade -y; apt-get -f install vim'

#jobs:
#  include:
#   - stage: building ppc64le image
#     arch: ppc64le
#     script: chmod +x ./build.sh; ./build.sh
   #- stage: building x86_64 image
   #  arch: amd64
   #  script: chmod +x ./build.sh; ./build.sh
  # - stage: building multi-arch image
   #  arch: ppc64le
   #  script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
   #- stage: run x86_64 image
   #  arch: amd64
   #  script: docker pull quay.io/rpsene/multi-arch-travis:latest; docker run --rm quay.io/rpsene/multi-arch-travis:latest
   #- stage: run ppc64le image
   #  arch: ppc64le
   #  script: docker pull quay.io/rpsene/multi-arch-travis:latest; docker run --rm quay.io/rpsene/multi-arch-travis:latest
